apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployapp
  labels:
    app: deployapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployapp
  template:
    metadata:
      labels:
        app: deployapp
    spec:
      containers:
      - name: 
        image: subashdocker07/flower:v3
        ports:
        - containerPort: 80
