apiVersion: v1
kind: Service
metadata:
  name: deployapp
  labels:
    app: deployapp
spec:
  ports:
    - port: 8080
      targetPort: 80
      nodeport: 31560

  selector:
    app: deployapp
  type: LoadBalancer
      
